### ISSUE TITLE
Failure should support arbitrary Throwables instead of RuntimeException

### ISSUE THREAD

**Issue by jhorstmann** [zalando/switchboard#8]
This can probably be done quite easy by doing the wrapping in `ExecutionException` inside of `Failure` instead of `Answer`.

**Comment by whiskeysierra** [comment]
So you would propagate
- `RuntimeException` *as-is*
- `Exception` wrapped in `ExecutionException`?

**Comment by jhorstmann** [comment]
I would prefer to always wrap the exception, similar to how it is done with `InvocationTargetException`.

**Comment by whiskeysierra** [comment]
Fixed by #9
